on:
  pull_request:
  push:
    branches:
      - main

name: Test

jobs:
  test:
    name: Cargo test
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Test 
        run: cargo test --workspace --all-targets --all-features
  cargo-miri-test:
    name: Cargo miri
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Setup miri
        run: |
          rustup toolchain install nightly --component miri;
          rustup override set nightly;
          cargo miri setup;

      - name: Test with Miri
        run: cargo miri test --workspace --all-targets --all-features MIRIFLAGS=-Zmiri-isolation-error=warn